language: node_js
node_js:
  - 11.6.0
# can be multiple
cache: npm

#travis lifecycle methods
before_install:
  - echo "before_install"
install:
  - npm install
before_script:
  - echo "before_script"
script:
  - npm run test
after_success:
  - echo "after_success"
after_failure:
  - echo "after_failure"
after_script:
  - echo "after_script"
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "cicdgitlab"
  env: "cicdenv"
